*** Starting uWSGI 0.9.9.2 (64bit) on [Mon Oct 24 11:14:28 2011] ***
compiled with version: 4.4.3 on 25 September 2011 14:54:58
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
setuid() to 33
your memory page size is 4096 bytes
uwsgi socket 0 bound to UNIX address /var/www/mozbuzzdjangoapp.socket fd 4
Python version: 2.6.5 (r265:79063, Apr 16 2010, 14:15:55)  [GCC 4.4.3]
Python main interpreter initialized at 0x24d8730
your server socket listen backlog is limited to 100 connections
*** Operational MODE: preforking ***
added ../ to pythonpath.
added /var/www/ to pythonpath.
added /var/lib/ to pythonpath.
added /var/lib/mozbuzz/ to pythonpath.
WSGI application 0 (mountpoint=) ready on interpreter 0x24d8730 pid: 32549 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 32549)
spawned uWSGI worker 1 (pid: 32550, cores: 1)
spawned uWSGI worker 2 (pid: 32551, cores: 1)
spawned uWSGI worker 3 (pid: 32552, cores: 1)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 250, in __call__
    self.load_middleware()
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 45, in load_middleware
    mod = import_module(mw_module)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/usr/local/lib/python2.6/dist-packages/staticgenerator-1.4.1-py2.6.egg/staticgenerator/middleware.py", line 5, in <module>
    class StaticGeneratorMiddleware(object):
  File "/usr/local/lib/python2.6/dist-packages/staticgenerator-1.4.1-py2.6.egg/staticgenerator/middleware.py", line 17, in StaticGeneratorMiddleware
    urls = tuple([re.compile(url) for url in settings.STATIC_GENERATOR_URLS])
  File "/usr/lib/python2.6/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.6/re.py", line 245, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat
[pid: 32552|app: 0|req: 1/1] 212.166.209.18 () {44 vars in 1683 bytes} [Mon Oct 24 12:23:50 2011] GET /mozbuzz => generated 0 bytes in 253 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 250, in __call__
    self.load_middleware()
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 45, in load_middleware
    mod = import_module(mw_module)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/usr/local/lib/python2.6/dist-packages/staticgenerator-1.4.1-py2.6.egg/staticgenerator/middleware.py", line 5, in <module>
    class StaticGeneratorMiddleware(object):
  File "/usr/local/lib/python2.6/dist-packages/staticgenerator-1.4.1-py2.6.egg/staticgenerator/middleware.py", line 17, in StaticGeneratorMiddleware
    urls = tuple([re.compile(url) for url in settings.STATIC_GENERATOR_URLS])
  File "/usr/lib/python2.6/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.6/re.py", line 245, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat
[pid: 32552|app: 0|req: 2/2] 212.166.209.18 () {44 vars in 1695 bytes} [Mon Oct 24 12:23:56 2011] GET /mozbuzz/admin => generated 0 bytes in 4 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 250, in __call__
    self.load_middleware()
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 45, in load_middleware
    mod = import_module(mw_module)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/usr/local/lib/python2.6/dist-packages/staticgenerator-1.4.1-py2.6.egg/staticgenerator/middleware.py", line 5, in <module>
    class StaticGeneratorMiddleware(object):
  File "/usr/local/lib/python2.6/dist-packages/staticgenerator-1.4.1-py2.6.egg/staticgenerator/middleware.py", line 17, in StaticGeneratorMiddleware
    urls = tuple([re.compile(url) for url in settings.STATIC_GENERATOR_URLS])
  File "/usr/lib/python2.6/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.6/re.py", line 245, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat
[pid: 32552|app: 0|req: 3/3] 212.166.209.18 () {44 vars in 1697 bytes} [Mon Oct 24 12:24:00 2011] GET /mozbuzz/admin/ => generated 0 bytes in 1 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 250, in __call__
    self.load_middleware()
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 45, in load_middleware
    mod = import_module(mw_module)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/usr/local/lib/python2.6/dist-packages/staticgenerator-1.4.1-py2.6.egg/staticgenerator/middleware.py", line 5, in <module>
    class StaticGeneratorMiddleware(object):
  File "/usr/local/lib/python2.6/dist-packages/staticgenerator-1.4.1-py2.6.egg/staticgenerator/middleware.py", line 17, in StaticGeneratorMiddleware
    urls = tuple([re.compile(url) for url in settings.STATIC_GENERATOR_URLS])
  File "/usr/lib/python2.6/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.6/re.py", line 245, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat
[pid: 32552|app: 0|req: 4/4] 212.166.209.18 () {44 vars in 1709 bytes} [Mon Oct 24 12:24:11 2011] GET /mozbuzz/admin-media/ => generated 0 bytes in 1 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 250, in __call__
    self.load_middleware()
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 45, in load_middleware
    mod = import_module(mw_module)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/usr/local/lib/python2.6/dist-packages/staticgenerator-1.4.1-py2.6.egg/staticgenerator/middleware.py", line 5, in <module>
    class StaticGeneratorMiddleware(object):
  File "/usr/local/lib/python2.6/dist-packages/staticgenerator-1.4.1-py2.6.egg/staticgenerator/middleware.py", line 17, in StaticGeneratorMiddleware
    urls = tuple([re.compile(url) for url in settings.STATIC_GENERATOR_URLS])
  File "/usr/lib/python2.6/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.6/re.py", line 245, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat
[pid: 32551|app: 0|req: 1/5] 87.218.19.44 () {36 vars in 623 bytes} [Mon Oct 24 15:42:25 2011] GET /mozbuzz/ => generated 0 bytes in 637 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
*** Starting uWSGI 0.9.9.2 (64bit) on [Fri Oct 28 01:02:52 2011] ***
compiled with version: 4.4.3 on 25 September 2011 14:54:58
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
setuid() to 33
your memory page size is 4096 bytes
uwsgi socket 0 bound to UNIX address /var/www/mozbuzzdjangoapp.socket fd 4
Python version: 2.6.5 (r265:79063, Apr 16 2010, 14:15:55)  [GCC 4.4.3]
Python main interpreter initialized at 0x6686d0
your server socket listen backlog is limited to 100 connections
*** Operational MODE: preforking ***
added ../ to pythonpath.
added /var/www/ to pythonpath.
added /var/lib/ to pythonpath.
added /var/lib/mozbuzz/ to pythonpath.
WSGI application 0 (mountpoint=) ready on interpreter 0x6686d0 pid: 19960 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 19960)
spawned uWSGI worker 1 (pid: 19961, cores: 1)
spawned uWSGI worker 2 (pid: 19962, cores: 1)
spawned uWSGI worker 3 (pid: 19963, cores: 1)
/usr/lib/pymodules/python2.6/django/db/__init__.py:60: DeprecationWarning: Short names for ENGINE in database configurations are deprecated. Prepend default.ENGINE with 'django.db.backends.'
  DeprecationWarning
*** Warning ***: Using "localhost" for domain name. Use django.contrib.sites or set settings.SERVER_NAME to disable this warning.
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 272, in __call__
    response = self.get_response(request)
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 169, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 214, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/usr/lib/pymodules/python2.6/django/core/urlresolvers.py", line 274, in _get_urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/var/lib/mozevents/urls.py", line 5, in <module>
    admin.autodiscover()
  File "/usr/lib/pymodules/python2.6/django/contrib/admin/__init__.py", line 22, in autodiscover
    mod = import_module(app)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
ImportError: No module named django_countries
[pid: 19962|app: 0|req: 1/1] 79.145.147.143 () {40 vars in 1198 bytes} [Fri Oct 28 01:02:58 2011] GET /mozbuzz/ => generated 0 bytes in 4647 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
/usr/lib/pymodules/python2.6/django/db/__init__.py:60: DeprecationWarning: Short names for ENGINE in database configurations are deprecated. Prepend default.ENGINE with 'django.db.backends.'
  DeprecationWarning
*** Warning ***: Using "localhost" for domain name. Use django.contrib.sites or set settings.SERVER_NAME to disable this warning.
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 272, in __call__
    response = self.get_response(request)
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 169, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 214, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/usr/lib/pymodules/python2.6/django/core/urlresolvers.py", line 274, in _get_urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/var/lib/mozevents/urls.py", line 5, in <module>
    admin.autodiscover()
  File "/usr/lib/pymodules/python2.6/django/contrib/admin/__init__.py", line 22, in autodiscover
    mod = import_module(app)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
ImportError: No module named django_countries
[pid: 19961|app: 0|req: 1/2] 79.145.147.143 () {40 vars in 1198 bytes} [Fri Oct 28 01:03:23 2011] GET /mozbuzz/ => generated 0 bytes in 1684 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 272, in __call__
    response = self.get_response(request)
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 169, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 214, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/usr/lib/pymodules/python2.6/django/core/urlresolvers.py", line 274, in _get_urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/var/lib/mozevents/urls.py", line 5, in <module>
    admin.autodiscover()
  File "/usr/lib/pymodules/python2.6/django/contrib/admin/__init__.py", line 22, in autodiscover
    mod = import_module(app)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
ImportError: No module named django_countries
[pid: 19961|app: 0|req: 2/3] 79.145.147.143 () {42 vars in 1229 bytes} [Fri Oct 28 01:07:24 2011] GET /mozbuzz/ => generated 0 bytes in 1238 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 272, in __call__
    response = self.get_response(request)
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 169, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 214, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/usr/lib/pymodules/python2.6/django/core/urlresolvers.py", line 274, in _get_urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/var/lib/mozevents/urls.py", line 5, in <module>
    admin.autodiscover()
  File "/usr/lib/pymodules/python2.6/django/contrib/admin/__init__.py", line 22, in autodiscover
    mod = import_module(app)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
ImportError: No module named django_countries
[pid: 19961|app: 0|req: 3/4] 95.18.103.244 () {40 vars in 1036 bytes} [Fri Oct 28 01:10:33 2011] GET /mozbuzz/static/blah.txt => generated 0 bytes in 1064 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 272, in __call__
    response = self.get_response(request)
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 169, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 214, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/usr/lib/pymodules/python2.6/django/core/urlresolvers.py", line 274, in _get_urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/var/lib/mozevents/urls.py", line 5, in <module>
    admin.autodiscover()
  File "/usr/lib/pymodules/python2.6/django/contrib/admin/__init__.py", line 22, in autodiscover
    mod = import_module(app)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
ImportError: No module named django_countries
[pid: 19961|app: 0|req: 4/5] 95.18.103.244 () {40 vars in 1006 bytes} [Fri Oct 28 01:10:36 2011] GET /mozbuzz/ => generated 0 bytes in 1203 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 272, in __call__
    response = self.get_response(request)
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 169, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 214, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/usr/lib/pymodules/python2.6/django/core/urlresolvers.py", line 274, in _get_urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/var/lib/mozevents/urls.py", line 5, in <module>
    admin.autodiscover()
  File "/usr/lib/pymodules/python2.6/django/contrib/admin/__init__.py", line 22, in autodiscover
    mod = import_module(app)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
ImportError: No module named django_countries
[pid: 19961|app: 0|req: 5/6] 95.18.103.244 () {44 vars in 1059 bytes} [Fri Oct 28 01:10:50 2011] GET /mozbuzz/ => generated 0 bytes in 1099 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 272, in __call__
    response = self.get_response(request)
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 169, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 214, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/usr/lib/pymodules/python2.6/django/core/urlresolvers.py", line 274, in _get_urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/var/lib/mozevents/urls.py", line 5, in <module>
    admin.autodiscover()
  File "/usr/lib/pymodules/python2.6/django/contrib/admin/__init__.py", line 22, in autodiscover
    mod = import_module(app)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
ImportError: No module named django_countries
[pid: 19961|app: 0|req: 6/7] 79.145.147.143 () {42 vars in 1229 bytes} [Fri Oct 28 01:10:53 2011] GET /mozbuzz/ => generated 0 bytes in 1129 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 272, in __call__
    response = self.get_response(request)
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 169, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 214, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/usr/lib/pymodules/python2.6/django/core/urlresolvers.py", line 274, in _get_urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/var/lib/mozevents/urls.py", line 5, in <module>
    admin.autodiscover()
  File "/usr/lib/pymodules/python2.6/django/contrib/admin/__init__.py", line 22, in autodiscover
    mod = import_module(app)
  File "/usr/lib/pymodules/python2.6/django/utils/importlib.py", line 35, in import_module
    __import__(name)
ImportError: No module named django_countries
[pid: 19961|app: 0|req: 7/8] 95.18.103.244 () {40 vars in 1036 bytes} [Fri Oct 28 01:11:06 2011] GET /mozbuzz/static/blah.txt => generated 0 bytes in 1071 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
*** Starting uWSGI 0.9.9.2 (64bit) on [Fri Oct 28 01:13:10 2011] ***
compiled with version: 4.4.3 on 25 September 2011 14:54:58
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
setuid() to 33
your memory page size is 4096 bytes
uwsgi socket 0 bound to UNIX address /var/www/mozbuzzdjangoapp.socket fd 4
Python version: 2.6.5 (r265:79063, Apr 16 2010, 14:15:55)  [GCC 4.4.3]
Python main interpreter initialized at 0xf0d730
your server socket listen backlog is limited to 100 connections
*** Operational MODE: preforking ***
added ../ to pythonpath.
added /var/www/ to pythonpath.
added /var/lib/ to pythonpath.
added /var/lib/mozbuzz/ to pythonpath.
WSGI application 0 (mountpoint=) ready on interpreter 0xf0d730 pid: 20093 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 20093)
spawned uWSGI worker 1 (pid: 20094, cores: 1)
spawned uWSGI worker 2 (pid: 20095, cores: 1)
spawned uWSGI worker 3 (pid: 20096, cores: 1)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 250, in __call__
    self.load_middleware()
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 39, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/usr/lib/pymodules/python2.6/django/utils/functional.py", line 276, in __getattr__
    self._setup()
  File "/usr/lib/pymodules/python2.6/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/pymodules/python2.6/django/conf/__init__.py", line 89, in __init__
    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
ImportError: Could not import settings 'mozbuzz.settings' (Is it on sys.path?): No module named settings_local
[pid: 20094|app: 0|req: 1/1] 95.18.103.244 () {44 vars in 1089 bytes} [Fri Oct 28 01:13:12 2011] GET /mozbuzz/static/blah.txt => generated 0 bytes in 36 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 250, in __call__
    self.load_middleware()
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 39, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/usr/lib/pymodules/python2.6/django/utils/functional.py", line 276, in __getattr__
    self._setup()
  File "/usr/lib/pymodules/python2.6/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/pymodules/python2.6/django/conf/__init__.py", line 89, in __init__
    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
ImportError: Could not import settings 'mozbuzz.settings' (Is it on sys.path?): No module named settings_local
[pid: 20094|app: 0|req: 2/2] 79.145.147.143 () {42 vars in 1229 bytes} [Fri Oct 28 01:13:50 2011] GET /mozbuzz/ => generated 0 bytes in 1 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 250, in __call__
    self.load_middleware()
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 39, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/usr/lib/pymodules/python2.6/django/utils/functional.py", line 276, in __getattr__
    self._setup()
  File "/usr/lib/pymodules/python2.6/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/pymodules/python2.6/django/conf/__init__.py", line 89, in __init__
    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
ImportError: Could not import settings 'mozbuzz.settings' (Is it on sys.path?): No module named settings_local
[pid: 20094|app: 0|req: 3/3] 95.18.103.244 () {44 vars in 1089 bytes} [Fri Oct 28 01:14:44 2011] GET /mozbuzz/static/blah.txt => generated 0 bytes in 1 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 250, in __call__
    self.load_middleware()
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 39, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/usr/lib/pymodules/python2.6/django/utils/functional.py", line 276, in __getattr__
    self._setup()
  File "/usr/lib/pymodules/python2.6/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/pymodules/python2.6/django/conf/__init__.py", line 89, in __init__
    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
ImportError: Could not import settings 'mozbuzz.settings' (Is it on sys.path?): No module named settings_local
[pid: 20094|app: 0|req: 4/4] 95.18.103.244 () {40 vars in 1006 bytes} [Fri Oct 28 01:14:46 2011] GET /mozbuzz/ => generated 0 bytes in 1 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/django/core/handlers/wsgi.py", line 250, in __call__
    self.load_middleware()
  File "/usr/lib/pymodules/python2.6/django/core/handlers/base.py", line 39, in load_middleware
    for middleware_path in settings.MIDDLEWARE_CLASSES:
  File "/usr/lib/pymodules/python2.6/django/utils/functional.py", line 276, in __getattr__
    self._setup()
  File "/usr/lib/pymodules/python2.6/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/pymodules/python2.6/django/conf/__init__.py", line 89, in __init__
    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
ImportError: Could not import settings 'mozbuzz.settings' (Is it on sys.path?): No module named settings_local
[pid: 20094|app: 0|req: 5/5] 79.145.147.143 () {42 vars in 1229 bytes} [Fri Oct 28 01:15:26 2011] GET /mozbuzz/ => generated 0 bytes in 1 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
*** Starting uWSGI 0.9.9.2 (64bit) on [Fri Oct 28 01:17:52 2011] ***
compiled with version: 4.4.3 on 25 September 2011 14:54:58
detected binary path: /usr/local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
setuid() to 33
your memory page size is 4096 bytes
uwsgi socket 0 bound to UNIX address /var/www/mozbuzzdjangoapp.socket fd 4
Python version: 2.6.5 (r265:79063, Apr 16 2010, 14:15:55)  [GCC 4.4.3]
Python main interpreter initialized at 0x1df5730
your server socket listen backlog is limited to 100 connections
*** Operational MODE: preforking ***
added ../ to pythonpath.
added /var/www/ to pythonpath.
added /var/lib/ to pythonpath.
added /var/lib/mozbuzz/ to pythonpath.
WSGI application 0 (mountpoint=) ready on interpreter 0x1df5730 pid: 20127 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 20127)
spawned uWSGI worker 1 (pid: 20128, cores: 1)
spawned uWSGI worker 2 (pid: 20129, cores: 1)
spawned uWSGI worker 3 (pid: 20130, cores: 1)
[pid: 20128|app: 0|req: 1/1] 95.18.103.244 () {44 vars in 1059 bytes} [Thu Oct 27 18:17:56 2011] GET /mozbuzz/ => generated 2015 bytes in 232 msecs (HTTP/1.1 404) 1 headers in 51 bytes (1 switches on core 0)
[pid: 20128|app: 0|req: 2/2] 95.18.103.244 () {40 vars in 1020 bytes} [Thu Oct 27 18:18:06 2011] GET /mozbuzz/static/ => generated 2036 bytes in 5 msecs (HTTP/1.1 404) 1 headers in 51 bytes (1 switches on core 0)
[pid: 20130|app: 0|req: 1/3] 79.145.147.143 () {42 vars in 1229 bytes} [Thu Oct 27 18:18:06 2011] GET /mozbuzz/ => generated 2015 bytes in 154 msecs (HTTP/1.1 404) 1 headers in 51 bytes (1 switches on core 0)
[pid: 20128|app: 0|req: 3/4] 190.16.189.36 () {40 vars in 1062 bytes} [Thu Oct 27 18:22:32 2011] GET /mozbuzz/ => generated 2015 bytes in 7 msecs (HTTP/1.1 404) 1 headers in 51 bytes (1 switches on core 0)
[pid: 20128|app: 0|req: 4/5] 190.16.189.36 () {40 vars in 1074 bytes} [Thu Oct 27 18:22:40 2011] GET /mozbuzz/admin/ => generated 2033 bytes in 5 msecs (HTTP/1.1 404) 1 headers in 51 bytes (1 switches on core 0)
[pid: 20128|app: 0|req: 5/6] 190.16.189.36 () {40 vars in 1074 bytes} [Thu Oct 27 18:22:43 2011] GET /mozbuzz/admin/ => generated 2033 bytes in 8 msecs (HTTP/1.1 404) 1 headers in 51 bytes (1 switches on core 0)
[pid: 20128|app: 0|req: 6/7] 190.16.189.36 () {40 vars in 1074 bytes} [Thu Oct 27 18:22:46 2011] GET /mozbuzz/admin/ => generated 2033 bytes in 7 msecs (HTTP/1.1 404) 1 headers in 51 bytes (1 switches on core 0)
